server:
  port: 8080

spring:
  datasource:
        url: jdbc:mysql://localhost:3306/study_ssm
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

knife4j:
  # 是否停用Knife4j文档
  # knife4j.production	false	是否开启生产环境保护策略,详情参考文档
  production: true
  # 注意：要使用Knife4j提供的增强，knife4j.enable=true必须开启
  # knife4j.enable	默认是 false     是否开启Knife4j增强模式
  enable: false
